### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by camjac251** [milasoftwaregroup/imago#4]
I think I missed something during setup. I made a postgresql db and username but when I view the table for users, nothing shows up. Is there an installer setup that I should run? I get redirected to `/api/login` but never signed up.

**Comment by Jack-Gledhill** [comment]
You need to configure a superuser in the config.yml file. Then you need to login using the configured username and password, after that click the Lock icon in the top right and create a user from there.

**Comment by camjac251** [comment]
Does it work with the defaults in the example?

Should this work with username superuser and pass youshallnotpass?
```
# ================
# Superuser config
# ================
superuser:
    username: superuser
    password: youshallnotpass

    display_name: Administrator
    api_token: Master youshallnotpass
```
